# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- releases/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  image.version: '3.0.2'
  imageName: 'ffmpeg:$(build.buildId)'
  taggedImage: 'ffmpeg:$(image.version)'
  latestImage: 'ffmpeg:latest'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'build image'
- script: docker run -t $(imageName) ffmpeg -buildconf
  displayName: 'validate built image'
- script: |
    docker login -u $(dockerId) -p $(dockerPassword)
    docker tag $(imageName) $(dockerRepoId)/$(taggedImage)
    docker tag $(imageName) $(dockerRepoId)/$(latestImage)
    docker push $(dockerRepoId)/$(taggedImage)
    docker push $(dockerRepoId)/$(latestImage)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/releases'))
  displayName: 'push image to dockerhub'
