# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- devel

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'ffmpeg'
  buildImage: $(imageName):$(build.buildId)

steps:
- script: docker build -f Dockerfile -t $(buildImage) .
  displayName: 'build image'
- script: docker run -t $(buildImage) -buildconf
  displayName: 'validate built image'
- script: |
    chmod +x version.sh
    docker login -u $(dockerId) -p $(dockerPassword)
    docker tag $(buildImage) $(dockerRepoId)/$(imageName):$(./version.sh)
    docker tag $(buildImage) $(dockerRepoId)/$(imageName):latest
    docker push $(dockerRepoId)/$(imageName):$(./version.sh)
    docker push $(dockerRepoId)/$(imageName):latest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'push image to dockerhub'
